logging:
  file: heroesbackend.log
  level:
    org.hibernate: INFO
    io.navan: DEBUG
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
